### ISSUE TITLE
No sound on Ubuntu 22

### ISSUE THREAD

**Issue by dekar91** [Vocab-Apps/anki-awesome-tts#1]
Hi! I faced a problem: the audio does not play on Ubuntu 22 with the latest Anki version. My Windows and Android devices work normally. 

There is my debug log:

```
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.5.0-35-generic-x86_64-with-glibc2.35

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.sound", line 298, in <lambda>
  File "aqt.sound", line 353, in _on_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.sound", line 297, in <lambda>
  File "aqt.sound", line 489, in _play
  File "aqt.sound", line 326, in _wait_for_termination
  File "subprocess", line 1189, in wait
  File "subprocess", line 1925, in _wait
subprocess.TimeoutExpired: Command '['mplayer', '-really-quiet', '-noautosub', '-slave', '/home/user/.local/share/Anki2/addons21/1436550454/user_files/cache/google-be6132e2-08152ccf-defc2add-583d0b2a-ef3acb92.mp3']' timed out after 1 seconds

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-05-25T02:24, 'None', '']

===IDs of active AnkiWeb add-ons===
1436550454

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```

Any ideas how I could fix it?

**Comment by luc-vocab** [comment]
Are you able to play any sounds at all ?
